const $ = id => document.getElementById(id);
const svg = body => 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 160">${body}</svg>`);
const eyes = '<circle cx="67" cy="79" r="4" fill="#23394b"/><circle cx="94" cy="79" r="4" fill="#23394b"/><path d="M70 95 Q80 105 91 95" fill="none" stroke="#23394b" stroke-width="3" stroke-linecap="round"/>';
const assets = [
 {name:'快樂小花',src:svg('<g fill="#ffba4d"><circle cx="80" cy="35" r="25"/><circle cx="120" cy="57" r="25"/><circle cx="120" cy="104" r="25"/><circle cx="80" cy="127" r="25"/><circle cx="40" cy="104" r="25"/><circle cx="40" cy="57" r="25"/></g><circle cx="80" cy="81" r="37" fill="#fff3c1"/>'+eyes),ratio:1},
 {name:'奶油小貓',src:svg('<path d="M38 58 L31 20 L65 44 Q81 37 99 44 L130 21 L124 64 Q145 110 115 130 Q80 150 45 130 Q17 109 38 58" fill="#ffceae" stroke="#c28666" stroke-width="3"/><path d="M37 30 L44 54 L56 47 M122 32 L113 52 L104 47" fill="#f19caa"/>'+eyes+'<path d="M30 91 L55 96 M32 106 L54 105 M108 96 L134 91 M109 105 L131 107" stroke="#ad765a" stroke-width="2"/>'),ratio:1},
 {name:'放晴的雲',src:svg('<circle cx="111" cy="48" r="29" fill="#ffcc67"/><g stroke="#efb74b" stroke-width="4" stroke-linecap="round"><path d="M111 8V2 M145 21L151 15 M151 49H158"/></g><path d="M33 129 Q8 123 14 100 Q17 79 40 79 Q37 47 70 47 Q97 44 109 74 Q142 66 150 96 Q161 127 126 130Z" fill="#b9dcec"/>'+eyes),ratio:1.15},
 {name:'好日子',src:svg('<rect x="12" y="24" width="136" height="110" rx="28" fill="#b9dfd0"/><path d="M25 118Q80 131 136 118" fill="none" stroke="#86bda8" stroke-width="3"/><text x="80" y="71" text-anchor="middle" fill="#285850" font-size="29" font-family="sans-serif" font-weight="900">GOOD</text><text x="80" y="106" text-anchor="middle" fill="#285850" font-size="29" font-family="sans-serif" font-weight="900">DAYS</text>'),ratio:1.22},
 {name:'粉紅櫻桃',src:svg('<path d="M50 90 Q52 38 105 15 Q100 52 113 91" fill="none" stroke="#648e68" stroke-width="7" stroke-linecap="round"/><path d="M99 21 Q57 6 62 32 Q75 47 99 21" fill="#b0cf85"/><circle cx="49" cy="110" r="32" fill="#ed86a8"/><circle cx="116" cy="111" r="30" fill="#f49bb8"/><path d="M31 99 Q32 90 42 87 M99 103 Q100 92 110 90" fill="none" stroke="#ffd6e5" stroke-width="6" stroke-linecap="round"/>'),ratio:1},
 {name:'慢慢喝咖啡',src:svg('<path d="M118 57 H132 Q153 61 147 84 Q144 104 122 104" fill="none" stroke="#92b1d6" stroke-width="10"/><path d="M26 52 H124 L119 116 Q75 149 31 116Z" fill="#bdd4ef"/><ellipse cx="75" cy="53" rx="49" ry="13" fill="#92b1d6"/><ellipse cx="75" cy="54" rx="41" ry="8" fill="#806751"/><path d="M57 32 Q47 23 60 14 M85 31 Q75 19 88 8" fill="none" stroke="#bac8d5" stroke-width="5" stroke-linecap="round"/>'+eyes),ratio:1.08}
];
let items=[], selected=null, history=[], future=[];
let sequence=0, toastTimer;
const initialPositions=[[28,27],[112,26],[103,100],[25,115],[30,198],[109,200]];
const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
function makeItem(asset,index=0){const w=asset.ratio>1?54:48;return {id:++sequence,...asset,w,border:2,x:initialPositions[index%6][0],y:initialPositions[index%6][1],rotation:[-12,10,7,-8,-8,12][index%6]};}
function snapshot(){history.push(JSON.stringify(items));if(history.length>30)history.shift();future=[];}
function notify(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3200);}
function outline(mm){const px=mm*$('paper').clientWidth/210;return [[px,0],[-px,0],[0,px],[0,-px],[px*.7,px*.7],[-px*.7,px*.7],[px*.7,-px*.7],[-px*.7,-px*.7]].map(([x,y])=>`drop-shadow(${x}px ${y}px 0 white)`).join(' ');}
function selectedItem(){return items.find(i=>i.id===selected);}
function render(){
 $('stickers').replaceChildren();
 for(const item of items){const el=document.createElement('button');el.className='sticker'+(selected===item.id?' selected':'');el.dataset.id=item.id;el.setAttribute('aria-label',`編輯${item.name}`);el.style.cssText=`left:${item.x/210*100}%;top:${item.y/297*100}%;width:${item.w/210*100}%;height:${(item.w/item.ratio)/297*100}%;transform:rotate(${item.rotation}deg);--outline:${outline(item.border)}`;const img=document.createElement('img');img.src=item.src;img.alt='';img.draggable=false;el.append(img);el.addEventListener('pointerdown',e=>startDrag(e,item,el));el.addEventListener('click',()=>{selected=item.id;render();});el.addEventListener('keydown',e=>{const moves={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(moves[e.key]){e.preventDefault();snapshot();moveItem(item,item.x+moves[e.key][0],item.y+moves[e.key][1]);selected=item.id;render();document.querySelector(`[data-id="${item.id}"]`)?.focus();}});$('stickers').append(el);}
 $('layout-status').textContent=`已放入 ${items.length} 張貼紙`;
 $('undo').disabled=!history.length;$('redo').disabled=!future.length;
 const item=selectedItem();$('selected-preview').replaceChildren();
 if(item){const image=document.createElement('img');image.src=item.src;image.alt=item.name;$('selected-preview').append(image);$('selected-name').textContent=item.name;$('width').value=item.w;$('border').value=item.border;$('border-value').textContent=item.border.toFixed(1)+' mm';const dpi=item.pixels?Math.round(item.pixels/(item.w/25.4)):null;const badge=$('dpi-badge');badge.textContent=dpi?`${dpi} DPI ${dpi>=300?'清晰':dpi>=150?'普通':'偏低'}`:'向量素材';badge.className='quality'+(dpi&&dpi<150?' bad':dpi&&dpi<300?' warn':'');}
 else{$('selected-name').textContent='點選畫布上的貼紙';$('dpi-badge').textContent='';}
 for(const id of ['width','border','duplicate','delete'])$(id).disabled=!item;
 updatePrice();
}
// Reserve extra room around the rotated bounding box and preview border.
function moveItem(item,x,y){const r=Math.abs(item.rotation)*Math.PI/180,h=item.w/item.ratio;const boxW=item.w*Math.cos(r)+h*Math.sin(r),boxH=h*Math.cos(r)+item.w*Math.sin(r);const dx=(boxW-item.w)/2+item.border,dy=(boxH-h)/2+item.border;item.x=clamp(x,15+dx,195-item.w-dx);item.y=clamp(y,23.5+dy,273.5-h-dy);}
function startDrag(e,item,el){if(e.button!==0)return;e.preventDefault();selected=item.id;document.querySelectorAll('.sticker').forEach(n=>n.classList.toggle('selected',n===el));const start={x:e.clientX,y:e.clientY,ix:item.x,iy:item.y},scale=$('paper').clientWidth/210;let changed=false;el.setPointerCapture(e.pointerId);const move=ev=>{if(!changed&&Math.hypot(ev.clientX-start.x,ev.clientY-start.y)>2){snapshot();changed=true;}if(changed){moveItem(item,start.ix+(ev.clientX-start.x)/scale,start.iy+(ev.clientY-start.y)/scale);el.style.left=item.x/210*100+'%';el.style.top=item.y/297*100+'%';}};const end=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',end);render();};el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);}
function addAsset(asset){if(items.length>=40){notify('每張貼紙板最多放入 40 個素材。');return;}snapshot();const item=makeItem(asset,items.length);moveItem(item,item.x,item.y);items.push(item);selected=item.id;render();notify('已加入貼紙，可拖曳調整位置。');}
function renderAssets(){$('asset-grid').replaceChildren();for(const asset of assets){const btn=document.createElement('button');btn.className='asset-tile';btn.setAttribute('aria-label',`加入${asset.name}`);const image=document.createElement('img');image.src=asset.src;image.alt=asset.name;btn.append(image);btn.onclick=()=>addAsset(asset);$('asset-grid').append(btn);}$('asset-count').textContent=assets.length+' 張';}
async function upload(files){for(const file of files){if(!['image/png','image/jpeg','image/webp'].includes(file.type)){notify('請選擇 JPG、PNG 或 WebP 圖片。');continue;}if(file.size>25*1024*1024){notify(`${file.name} 超過 25 MB，請先縮小檔案。`);continue;}if(items.length>=40){notify('每張貼紙板最多放入 40 個素材。');break;}try{const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});const image=new Image();image.src=src;await image.decode();if(!image.naturalWidth||!image.naturalHeight)throw Error();const ratio=image.naturalWidth/image.naturalHeight;if(ratio<.25||ratio>4){notify('圖片過長，請裁切為寬高比例 1:4 至 4:1。');continue;}const asset={name:file.name.replace(/\.[^.]+$/,''),src,ratio,pixels:image.naturalWidth};assets.push(asset);renderAssets();addAsset(asset);}catch{notify('無法讀取圖片，請換一個檔案再試。');}}$('upload').value='';}
$('upload').onchange=e=>upload(e.target.files);
for(const type of ['dragover','dragleave','drop'])$('drop-zone').addEventListener(type,e=>{e.preventDefault();$('drop-zone').classList.toggle('dragover',type==='dragover');if(type==='drop')upload(e.dataTransfer.files);});
$('width').onchange=()=>{const item=selectedItem();if(!item)return;snapshot();item.w=clamp(Number($('width').value)||15,15,Math.min(100,200*item.ratio));moveItem(item,item.x,item.y);render();};
$('border').addEventListener('pointerdown',()=>{if(selectedItem())snapshot();});$('border').addEventListener('keydown',e=>{if(e.key.startsWith('Arrow'))snapshot();});$('border').oninput=()=>{const item=selectedItem();if(!item)return;item.border=Number($('border').value);moveItem(item,item.x,item.y);render();};
$('duplicate').onclick=()=>{const item=selectedItem();if(!item)return;if(items.length>=40){notify('每張貼紙板最多放入 40 個素材。');return;}snapshot();const next={...item,id:++sequence};moveItem(next,item.x+10,item.y+10);items.push(next);selected=next.id;render();};
$('delete').onclick=()=>{if(!selectedItem())return;snapshot();items=items.filter(i=>i.id!==selected);selected=items[0]?.id??null;render();};
$('undo').onclick=()=>{if(!history.length)return;future.push(JSON.stringify(items));items=JSON.parse(history.pop());selected=items[0]?.id??null;render();};$('redo').onclick=()=>{if(!future.length)return;history.push(JSON.stringify(items));items=JSON.parse(future.pop());selected=items[0]?.id??null;render();};
$('pack').onclick=()=>{let x=15,y=23.5,rowHeight=0;const packed=[];for(const item of items){const w=item.w+2*item.border,h=item.w/item.ratio+2*item.border;if(x+w>195){x=15;y+=rowHeight+3;rowHeight=0;}if(y+h>273.5){notify('這張紙排不下，請縮小貼紙或移除部分素材。');return;}packed.push({...item,x:x+item.border,y:y+item.border,rotation:0});x+=w+3;rowHeight=Math.max(rowHeight,h);}snapshot();items=packed;render();notify('已排列完成，貼紙白邊之間保留至少 3 mm。');};
$('toggle-guides').onclick=()=>{const hide=$('paper').classList.toggle('hide-guides');$('toggle-guides').textContent=hide?'顯示安全線':'隱藏安全線';$('toggle-guides').setAttribute('aria-pressed',String(!hide));};
function updatePrice(){const qty=clamp(Math.round(Number($('quantity').value)||1),1,99);$('quantity').value=qty;$('price').textContent=(qty*200).toLocaleString();}
$('quantity').onchange=updatePrice;$('minus').onclick=()=>{$('quantity').value=Number($('quantity').value)-1;updatePrice();};$('plus').onclick=()=>{$('quantity').value=Number($('quantity').value)+1;updatePrice();};
$('save').onclick=()=>{try{localStorage.setItem('enjoy-sticker-draft',JSON.stringify({items,finish:document.querySelector('[name="finish"]:checked').value,quantity:Number($('quantity').value)}));notify('草稿已儲存在這個瀏覽器，下次開啟會自動載入。');}catch{notify('瀏覽器儲存空間不足，請減少上傳圖片後重試。');}};
function modal(html){$('modal-content').innerHTML=html;$('modal').showModal();}$('close-modal').onclick=()=>$('modal').close();$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('modal').close();}});
$('guide').onclick=()=>modal('<span class="modal-icon">✦</span><h2>一張貼紙板，這樣做</h2><ol><li>上傳照片，或點選示範素材。</li><li>拖曳貼紙，調整尺寸與白邊。</li><li>用自動排版，將貼紙放入安全區。</li><li>選擇表面觸感與印製張數。</li></ol><p>此原型的上傳照片會保留原背景。AI 去背與正式訂製服務將於後續開發。</p>');
$('checkout').onclick=()=>{if(!items.length){notify('先加入一張貼紙，再確認貼紙板。');return;}const low=items.filter(i=>i.pixels&&i.pixels/(i.w/25.4)<150).length;const finish=document.querySelector('[name="finish"]:checked').value==='matte'?'霧面':'亮面';modal(`<span class="modal-icon">✧</span><h2>你的貼紙板，準備好了。</h2><div class="summary">A4 白底防水貼紙 · ${finish}<br>${items.length} 個圖案 · ${$('quantity').value} 張<br>商品小計 NT$ ${$('price').textContent}</div>${low?`<p>${low} 張圖片低於 150 DPI，印製可能模糊，建議更換較清晰的圖片。</p>`:''}<p>這是訂製確認的介面預覽，目前尚未提供付款、運費計算或建立訂單。</p><button class="button primary" id="back-edit">返回繼續編輯</button>`);$('back-edit').onclick=()=>$('modal').close();};
try{const saved=JSON.parse(localStorage.getItem('enjoy-sticker-draft'));if(saved&&Array.isArray(saved.items)&&saved.items.length<=40&&saved.items.every(i=>Number.isFinite(i.id)&&Number.isFinite(i.w)&&i.w>=15&&i.w<=100&&Number.isFinite(i.x)&&Number.isFinite(i.y)&&Number.isFinite(i.ratio)&&i.ratio>=.25&&i.ratio<=4&&typeof i.src==='string'&&/^data:image\/(svg\+xml|png|jpeg|webp)[;,]/.test(i.src))){items=saved.items;sequence=Math.max(0,...items.map(i=>i.id));$('quantity').value=saved.quantity||1;const finish=document.querySelector(`[name="finish"][value="${saved.finish==='glossy'?'glossy':'matte'}"]`);finish.checked=true;for(const item of items){if(!assets.some(a=>a.src===item.src))assets.push({name:item.name,src:item.src,ratio:item.ratio,pixels:item.pixels});}}else items=assets.map(makeItem);}catch{items=assets.map(makeItem);}
selected=items[0]?.id??null;renderAssets();render();new ResizeObserver(()=>render()).observe($('paper'));
